package ExceptionHandling;

public class ExceptionClass1 {
	
	public static Functions fun=new Functions();

	public static void main(String[] args) {
		
		//1st Exception Arithmatic
		/*
		 * int a=10; int b=0; System.out.println(a/b);
		 */
	
		
		//2nd Exception arrayindex out of bound
		/*
		 * String[] str=new String[2]; str[2]= "Anand";
		 */
	
		//3rd Exception Nullpointerexception
		
		fun.fun1();
		
		
	
	}

}
